server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: home-renovation
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  
  # 静态资源配置
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
  
  # 关闭favicon.ico的默认处理
  mvc:
    favicon:
      enabled: false
  
  # 数据库配置
  datasource:
    dynamic:
      enabled: true #启用动态数据源，默认true
      primary: master #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      strict: false
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/lightHouse?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/lightHouse?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    #url: jdbc:mysql://127.0.0.1:3306/lightHouse?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
        postgresql:
          url: jdbc:postgresql://127.0.0.1:54321/plighthouse
          username: postgres
          password: 123456
          driver-class-name: org.postgresql.Driver

    hikari:
      pool-name: HikariCP
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

# MyBatis-Plus配置
mybatis-plus:
  # 配置mapper xml文件路径
  mapper-locations: classpath:mapper/**.xml
  # 配置MyBatis数据返回类型别名
  type-aliases-package: com.lighthouse.entity
  configuration:
    # 自动驼峰命名转换
    map-underscore-to-camel-case: true
    # 打印SQL语句
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      # 主键生成策略
      id-type: auto

#logging:
#  level:
#    com.lighthouse: DEBUG
#    org.springframework.web: DEBUG
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    com.lighthouse: DEBUG
    com.lighthouse.mapper: DEBUG
    org.springframework.jdbc: DEBUG
    com.baomidou.mybatisplus: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId}] [%X{ip}] %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId}] [%X{ip}] %logger{50} - %msg%n"

# 跨域配置

# 跨域配置
cors:
  allowed-origins: "*"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true


# knife4j api 文档配置
knife4j:
  production: false
  basic:
    enable: true
    username: admin
    password: deepseek!23
  enable: true
  setting:
    enable-open-api: true
    language: zh_cn
    enable-footer: false
    enable-swagger-models: false
---
spring:
  config:
    activate:
      on-profile: dev
  
logging:
  level:
    root: INFO
    com.lighthouse: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: WARN
    com.lighthouse: INFO 